### ISSUE TITLE
about apple/DFN5B-CLIP-ViT-H-14-384

### ISSUE THREAD

**Issue by ffhelly** [hkchengrex/MMAudio#12]
Bro, I have a question.
I checked HF's website and did not find the 384 model, only the 378 model. Will this have an impact?
Also, where do I need to place this model in my directory? I am on Ubuntu system.

**Comment by hkchengrex** [comment]
The 378 model should be the same as the 384 model. I am not sure why two different numbers were used. If you go to https://huggingface.co/apple/DFN5B-CLIP-ViT-H-14-378, under "model usage", they also specify apple/DFN5B-CLIP-ViT-H-14-384.

Anyway, the model should be downloaded automatically by open_clip. Does it not?

**Comment by bbecausereasonss** [comment]
The install instructions don't mention most of these:

Prompt outputs failed validation
MMAudioFeatureUtilsLoader:
- Value not in list: vae_model: 'mmaudio_vae_44k_fp16.safetensors' not in ['mmaudio_large_44k_v2.pth']
- Value not in list: clip_model: 'apple_DFN5B-CLIP-ViT-H-14-384_fp16.safetensors' not in ['mmaudio_large_44k_v2.pth']
- Value not in list: synchformer_model: 'mmaudio_synchformer_fp16.safetensors' not in ['mmaudio_large_44k_v2.pth']

**Comment by hkchengrex** [comment]
@bbecausereasonss You are probably referring to https://github.com/kijai/ComfyUI-MMAudio.
Not part of this repo.

**Comment by WeizhenEricFang** [comment]
@hkchengrex I manually downloaded the Hugging Face model apple/DFN5B-CLIP-ViT-H-14-384 and managed to load it locally with the following code:

`self.clip_model = create_model_from_pretrained(
    model_name='ViT-H-14-378',
    pretrained='/home/models/apple-DFN5B-CLIP-ViT-H-14-378/open_clip_pytorch_model.bin',
    return_transform=False
)`

It seems to work, but I’m not sure if this is the correct or recommended way to load the model. Could this method have any negative impact or lead to potential issues?

**Comment by hkchengrex** [comment]
@WeizhenEricFang  Does the automatic download not work? If it loads it should be fine.
