### ISSUE TITLE
About the training data

### ISSUE THREAD

**Issue by auzxb** [hkchengrex/MMAudio#13]
I am a little confused about the training data. The overall generalization ability of this model is the best among all current open source projects. What types of data sets were used and how many hours did it take?

**Comment by hkchengrex** [comment]
Temporary paper link: https://github.com/hkchengrex/MMAudio/releases/download/v0.1/mmaudio.pdf
tl;dr: standard VGGSound for video/audio/text, and WavCaps+AudioCaps for audio/text. All of these have also been used in (some) prior works :)
