### ISSUE TITLE
How long of a video clip ?

### ISSUE THREAD

**Issue by jonnytracker** [hkchengrex/MMAudio#14]
Length per gb ?

**Comment by hkchengrex** [comment]
It is nonlinear with a large constant (from model loading I assume). Some data points reported by `torch.cuda.max_memory_allocated()`:
8s: 5.89G
16s: 6.66G
32s: 7.19G
64s: 8.23G

But I don't recommend running on videos much longer than the training length (8s). The quality will degrade.
