### ISSUE TITLE
Mac support

### ISSUE THREAD

**Issue by cocktailpeanut** [hkchengrex/MMAudio#17]
This is such a great project that it deserves to be available to Mac users. Is there any chance that we can have MPS support?

**Comment by hkchengrex** [comment]
I don't have a Mac device and therefore could not test it. Most of the time I think we are passing this `device` around https://github.com/hkchengrex/MMAudio/blob/ec2de628a5f226f8b96aa7686339326c4a817e41/demo.py#L65

I think you can try changing that to `mps` and see if you encounter any errors. Pull requests to fix them are welcomed -- I cannot test them and therefore it would be quite inefficient for me to try to fix them.

**Comment by hkchengrex** [comment]
#19
