### ISSUE TITLE
Your server is down and the app is broken

### ISSUE THREAD

**Issue by cocktailpeanut** [hkchengrex/MMAudio#18]
@hkchengrex The model download URL is broken. See https://databank.illinois.edu/datafiles/i1pd9/download

Which means nothing is working with the app right now. Relevant part of the code https://github.com/hkchengrex/MMAudio/blob/main/mmaudio/utils/download_utils.py#L34

BTW I am curious why you guys are hosting this on the university server instead of a reliable and free huggingface. I think you should move to huggingface completely.

**Comment by hkchengrex** [comment]
Thank you for reporting this. I've changed the links to huggingface's.
The reason is that the university guarantees long-term storage, but huggingface does not.

**Comment by cocktailpeanut** [comment]
@hkchengrex just tried and can confirm it's fixed. Thank you!
