### ISSUE TITLE
what is the empty_string.pth in mmaudio.runner?

### ISSUE THREAD

**Issue by AAApu1215** [hkchengrex/MMAudio#22]
Excuse me, when i run training on example data by "OMP_NUM_THREADS=4 torchrun --standalone --nproc_per_node=1 train.py exp_id=debug compile=False  debug=True example_train=True  batch_size=1", it shows: 
<img width="449" alt="Snipaste_2024-12-26_22-13-34" src="https://github.com/user-attachments/assets/34d0169d-3a7d-4403-bafb-9617d569c3f1" /> . what is the empty_string.pth in mmaudio.runner?

**Comment by hkchengrex** [comment]
Ah thank you for reporting this. It is just the CLIP encoding of the empty string. You can download it here: https://github.com/hkchengrex/MMAudio/releases/tag/v0.1 and place it in `ext_weights`.

**Comment by hkchengrex** [comment]
I have updated the readme and included instructions for downloading this and other required model files.

**Comment by AAApu1215** [comment]
Thank you!
