### ISSUE TITLE
Not supporting FFMPEG v7 is a big issue

### ISSUE THREAD

**Issue by FurkanGozukara** [hkchengrex/MMAudio#5]
In every app we are using latest version of FFMPEG

but the app fails since it is forcing FFMPEG version 6 and it complicates to make installers for different platforms

now i am going to make auto downloader for version 6 and put into accurate folder

**Comment by hkchengrex** [comment]
That's a valid point. I hate it too. Let me keep this issue open and see if I can get rid of it.

**Comment by hkchengrex** [comment]
Fixed 0e73e45389a07ee4be6b5e72e24638358c59d3f8

**Comment by FurkanGozukara** [comment]
@hkchengrex i have spent hours to fix ffmpeg errors haha :D
