### ISSUE TITLE
You have introduced errors with pyproject.toml

### ISSUE THREAD

**Issue by Deathdadev** [hkchengrex/MMAudio#9]
tensordict>=0.6.2 doesnt actually exist, the pyproject.toml file needs to have tensordict==0.6.1

**Comment by hkchengrex** [comment]
Exists on pypi: https://pypi.org/project/tensordict/

We have relaxed it to >=0.6.1. Still curious as to why 0.6.2 does not work though.

**Comment by Deathdadev** [comment]
I have been making a pinokio script that clones this repo and I have had multiple users get the same error with tensordict change. That is why I added my own pyproject.toml file to fix this issue for them: https://github.com/Deathdadev/MMAudio

**Comment by Deathdadev** [comment]
![image](https://github.com/user-attachments/assets/2fcce315-935e-418d-a7d2-4e9ade066b85)

**Comment by hkchengrex** [comment]
Ah, this seems to be a Windows-specific problem. `0.6.2` is probably not built for Windows. I usually don't run code on Windows so I didn't know. Thank you for reporting this. Anyway, I hope that it works now with the relaxed version requirement.

**Comment by hkchengrex** [comment]
Right Windows is listed under `0.6.1`: https://pypi.org/project/tensordict/0.6.1/#files
but not under `0.6.2`: https://pypi.org/project/tensordict/#files

**Comment by Deathdadev** [comment]
ahh right that makes sense, thank you for relaxing the requirements
